name: Terraform Azure VM Deploy

on:
  workflow_dispatch:

jobs:

  terraform-init:

    name: Terraform Init
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Repository Structure
        run: |
          echo "Current directory:"
          pwd

          echo ""
          echo "Files and folders:"
          ls -la

          echo ""
          echo "Directory structure:"
          find . -maxdepth 4 -type d | sort

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./environment/dev
        run: terraform init
